export class Medicine {
	constructor(
		public id: number,
		public code: string,
		public name: string,
		public imageUrl: string,
		public pharmacyId: number,
		public pharmacyName: string,
		public quantity: number,
		public category: string,
		public withPrescription: boolean,
		public description: string,
		public composition: string,
		public price: number
	) {}
}

export const medicines: Medicine[] = [
	{
		id: 0,
		code: 'CODO 000',
		name: 'CODOLIPRANE 400 MG / 20 MG, Comprimé',
		imageUrl:
			'https://www.pharmanity.com/assets/img/parapharmacie/codoliprane-adultes-400-mg-20-mg-16-comprimes-secables-i28.jpg',
		pharmacyId: 0,
		pharmacyName: 'Pharmacie El Bayrouni',
		quantity: 0,
		category: 'Analgésique',
		withPrescription: false,
		description: 'Boîte de 16',
		composition: 'Paracétamol et Codéine',
		price: 20,
	},
	{
		id: 1,
		code: 'PROF 111',
		name: 'PROFENID 100MG, Comprimé pelliculé',
		imageUrl: 'https://www.onlinepharmacy.qa/img/products/21716/21716-C.jpg',
		pharmacyId: 4,
		pharmacyName: 'Pharmacie Principale',
		quantity: 3,
		category: 'Analgésique',
		withPrescription: false,
		description: 'Boîte de 10',
		composition: 'Paracétamol et Codéine',
		price: 120,
	},
	{
		id: 2,
		code: 'PAN 222',
		name: 'PANSORAL, Gel Buccal',
		imageUrl:
			'https://www.pharma-gdd.com/images/catalog/pictures/thumbnails/600/pierre-fabre-pansoral-gel-adulte-face.jpg',
		pharmacyId: 2,
		pharmacyName: 'Pharmacie Tanger',
		quantity: 3,
		category: 'Analgésique',
		withPrescription: true,
		description: 'Gel 1 tube de 15g',
		composition: 'Paracétamol et Codéine',
		price: 56,
	},
	{
		id: 3,
		code: 'code 333',
		name: 'RHUMIX, Sachet',
		imageUrl:
			'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAyi5gcSfAFcLRHDezlmM8kuUbxHxYGnLiSA&usqp=CAU',
		pharmacyId: 1,
		pharmacyName: 'Pharmacie Santé',
		quantity: 3,
		category: 'Analgésique',
		withPrescription: true,
		description: 'Boîte de 14',
		composition: 'Paracétamol et Codéine',
		price: 23,
	},
	{
		id: 4,
		code: 'code 444',
		name: 'ASPEGIC 500 MG, Poudre en Sachet',
		imageUrl:
			'https://www.pharma-gdd.com/images/catalog/pictures/thumbnails/600/aspegic-500-mg-douleur-et-fievre-20-sachets-face-1.jpg',
		pharmacyId: 3,
		pharmacyName: 'Pharmacie Beni Makada',
		quantity: 3,
		category: 'Analgésique',
		withPrescription: false,
		description: 'Poudre, 16 Sachet',
		composition: 'Paracétamol et Codéine',
		price: 135,
	},
	{
		id: 5,
		code: 'code 555',
		name: 'HUMEX 20 MG, Pastille',
		imageUrl: 'https://www.pharma-medicaments.com/media/3392911__008512700_1130_07072016.jpg',
		pharmacyId: 4,
		pharmacyName: 'Pharmacie Beni Makada',
		quantity: 3,
		category: 'Analgésique',
		withPrescription: false,
		description: 'Boite de 12',
		composition: 'Paracétamol et Codéine',
		price: 36,
	},
];
