export class Medicine {
	constructor(
		public id: number,
		public code: string,
		public name: string,
		public image: string,
		public pharmacyId: number,
		public pharmacyName: string,
		public category: string,
		public withPrescription: boolean,
		public description: string,
		public composition: string,
		public price: number
	) {}
}

export const medicines: Medicine[] = [
	{
		id: 0,
		code: 'CODO 000',
		name: 'CODOLIPRANE 400 MG / 20 MG, Comprimé',
		image: 'medicine.jpg',
		pharmacyId: 0,
		pharmacyName: 'Pharmacie El Bayrouni',
		category: 'Analgésique',
		withPrescription: false,
		description: 'Boîte de 16',
		composition: 'Paracétamol et Codéine',
		price: 20,
	},
	{
		id: 1,
		code: 'PROF 111',
		name: 'PROFENID 100MG, Comprimé pelliculé',
		image: 'medicine.jpg',
		pharmacyId: 4,
		pharmacyName: 'Pharmacie Principale',
		category: 'Analgésique',
		withPrescription: false,
		description: 'Boîte de 10',
		composition: 'Paracétamol et Codéine',
		price: 120,
	},
	{
		id: 2,
		code: 'PAN 222',
		name: 'PANSORAL, Gel Buccal',
		image: 'medicine.jpg',
		pharmacyId: 2,
		pharmacyName: 'Pharmacie Tanger',
		category: 'Analgésique',
		withPrescription: true,
		description: 'Gel 1 tube de 15g',
		composition: 'Paracétamol et Codéine',
		price: 56,
	},
	{
		id: 3,
		code: 'code 333',
		name: 'RHUMIX, Sachet',
		image: 'medicine.jpg',
		pharmacyId: 1,
		pharmacyName: 'Pharmacie Santé',
		category: 'Analgésique',
		withPrescription: true,
		description: 'Boîte de 14',
		composition: 'Paracétamol et Codéine',
		price: 23,
	},
	{
		id: 4,
		code: 'code 444',
		name: 'ASPEGIC 500 MG, Poudre en Sachet',
		image: 'medicine.jpg',
		pharmacyId: 3,
		pharmacyName: 'Pharmacie Beni Makada',
		category: 'Analgésique',
		withPrescription: false,
		description: 'Poudre, 16 Sachet',
		composition: 'Paracétamol et Codéine',
		price: 135,
	},
	{
		id: 5,
		code: 'code 555',
		name: 'MAL DE GORGE 20 MG, Pastille',
		image: 'medicine.jpg',
		pharmacyId: 4,
		pharmacyName: 'Pharmacie Beni Makada',
		category: 'Analgésique',
		withPrescription: false,
		description: 'Boite de 12',
		composition: 'Paracétamol et Codéine',
		price: 36,
	},
];
